apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cloudhawks
  description: CloudHawks Squad
spec:
  type: team
  profile:
    email: ch@wfscorp.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: equalizer
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: kanagaraj
spec:
  profile:
    displayName: Kanagaraj Muthukumarasamy
    email: arun@example.com
    picture: https://avatars.dicebear.com/api/avataaars/tara-macgovern@example.com.svg?background=%23fff
  memberOf: [cloudhawks]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mony.a
spec:
  profile:
    displayName: Mony Adey
    email: mony@example.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [cloudhawks]
---
# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [dragonfly]