apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dragonfly
  description: Dragonfly Squad - Owners of fbo360
spec:
  type: team
  profile:
    email: dragonfly@wfscorp.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: subdept
  members: [olga, arun]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: arun
spec:
  profile:
    displayName: Arun Chandrasekaran
    email: arun@example.com
    picture: https://avatars.dicebear.com/api/avataaars/tara-macgovern@example.com.svg?background=%23fff
  memberOf: [dragonfly]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: olga
spec:
  profile:
    displayName: Olga Danchenko
    email: olga@example.com
    picture: https://avatars.dicebear.com/api/avataaars/peadar-macmahon@example.com.svg?background=%23fff
  memberOf: [dragonfly]
---
# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [dragonfly]