apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: wfscorp
  description: World Fuel Services Corporation
  links:
    - url: https://www.wfscorp.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: World Fuel Services Corporation
    email: info@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [aviation, land]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: squads
  description: Squads in WFS
spec:
  targets:
    - ./dragonfly.yaml
    - ./supercito.yaml
    - ./cloudhawks.yaml
    - ./domains.yaml
    - ./tribes.yaml
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: olga
spec:
  profile:
    displayName: Olga Danchenko
    email: olga@example.com
    picture: https://avatars.dicebear.com/api/avataaars/peadar-macmahon@example.com.svg?background=%23fff
  memberOf: [dragonfly]